// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: bit-radio-sqline

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_name = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Panel5 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_name = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_name, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_name, 0);
    lv_obj_set_y(ui_name, -2);
    lv_obj_set_align(ui_name, LV_ALIGN_CENTER);
    lv_label_set_text(ui_name, "Bit Radio 1.0");
    lv_obj_set_style_text_color(ui_name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 10);
    lv_obj_set_height(ui_Panel2, 10);
    lv_obj_set_x(ui_Panel2, -58);
    lv_obj_set_y(ui_Panel2, -27);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel3, 10);
    lv_obj_set_height(ui_Panel3, 10);
    lv_obj_set_x(ui_Panel3, -58);
    lv_obj_set_y(ui_Panel3, 27);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel4 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel4, 10);
    lv_obj_set_height(ui_Panel4, 10);
    lv_obj_set_x(ui_Panel4, 58);
    lv_obj_set_y(ui_Panel4, -27);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel5 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel5, 10);
    lv_obj_set_height(ui_Panel5, 10);
    lv_obj_set_x(ui_Panel5, 58);
    lv_obj_set_y(ui_Panel5, 27);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_name = NULL;
    ui_Panel2 = NULL;
    ui_Panel3 = NULL;
    ui_Panel4 = NULL;
    ui_Panel5 = NULL;

}
